services:
  warehouse-app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    expose:
      - "9001"
    ports:
      - "9001:9001"
    env_file:
      - ./app/.env
    volumes:
      - ./app/routes:/var/www/routes
      - ./app/resources:/var/www/resources
      - ./app/app:/var/www/app
      - ./app/public:/var/www/public
      - ./app/composer.json:/var/www/composer.json
      - ./php/php.ini:/usr/local/etc/php/php.ini

      - app_vendor:/var/www/vendor
      - app_storage:/var/www/storage
      - app_cache:/var/www/bootstrap/cache
    networks:
      - warehouse
  postgres-wh:
    image: postgres:13
    container_name: postgres-wh-container
    environment:
      POSTGRES_DB: pallet
      POSTGRES_USER: pra
      POSTGRES_PASSWORD: prasetyo7
    ports:
      - "5433:5432"
    volumes:
      - postgres-wh-data:/var/lib/postgresql/data
    networks:
      - warehouse
  # Nginx Service
  nginx-wh:
    image: nginx:latest
    container_name: nginx-wh
    restart: unless-stopped
    tty: true
    ports:
      - "8181:80"
    volumes:
      - app_storage:/var/www/storage
      - ./app/public:/var/www/public
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/app.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - warehouse-app
    networks:
      - warehouse

networks:
  warehouse:
    driver: bridge

volumes:
  postgres-wh-data:
    driver: local