<?php

namespace App\Providers\Admin;

use App\Service\Admin\AdminService;
use App\Service\Admin\AdminServiceImpl;
use Illuminate\Contracts\Support\DeferrableProvider;
use Illuminate\Support\ServiceProvider;

class AdminServiceProvider extends ServiceProvider implements DeferrableProvider
{
    /**
     * Register services.
     */
    public function register(): void
    {
        $this->app->singleton(AdminService::class,AdminServiceImpl::class);

    }

    /**
     * Bootstrap services.
     */
    public function boot(): void
    {
        //
    }

    public function provides()
    {
        return [AdminService::class]; // TODO: Change the autogenerated stub
    }
}
