<?php

namespace App\Providers\Admin;

use App\Service\Admin\PalletService;
use App\Service\Admin\PalletServiceImpl;
use Illuminate\Contracts\Support\DeferrableProvider;
use Illuminate\Support\ServiceProvider;

class PalletServiceProvider extends ServiceProvider implements DeferrableProvider
{
    /**
     * Register services.
     */
    public function register(): void
    {
        $this->app->singleton(PalletService::class,PalletServiceImpl::class);

    }

    /**
     * Bootstrap services.
     */
    public function boot(): void
    {
        //
    }

    public function provides()
    {
        return [PalletService::class]; // TODO: Change the autogenerated stub
    }
}
