<?php

namespace App\Providers\Admin;

use App\Service\Admin\UserService;
use App\Service\Admin\UserServiceImpl;
use Illuminate\Contracts\Support\DeferrableProvider;
use Illuminate\Support\ServiceProvider;

class UserServiceProvider extends ServiceProvider implements DeferrableProvider
{
    /**
     * Register services.
     */
    public function register(): void
    {
        $this->app->singleton(UserService::class,UserServiceImpl::class);
    }

    /**
     * Bootstrap services.
     */
    public function boot(): void
    {
        //
    }
    public function provides()
    {
        return [UserService::class]; // TODO: Change the autogenerated stub
    }
}
