<?php

namespace App\Providers\Client;

use App\Service\Client\Checker1Service;
use App\Service\Client\ServiceImpl\Checker1ServiceImpl;
use Illuminate\Contracts\Support\DeferrableProvider;
use Illuminate\Support\ServiceProvider;

class Checker1ServiceProvider extends ServiceProvider implements DeferrableProvider
{
    /**
     * Register services.
     */
    public function register(): void
    {
        $this->app->singleton(Checker1Service::class,Checker1ServiceImpl::class);
    }

    /**
     * Bootstrap services.
     */
    public function boot(): void
    {
        //
    }

    public function provides()
    {
        return [Checker1Service::class]; // TODO: Change the autogenerated stub
    }
}
