<?php

namespace App\Providers\Client;

use App\Service\Client\CheckerService;
use App\Service\Client\ServiceImpl\CheckerServiceImpl;
use Illuminate\Contracts\Support\DeferrableProvider;
use Illuminate\Support\ServiceProvider;

class CheckerServiceProvider extends ServiceProvider implements DeferrableProvider
{
    /**
     * Register services.
     */
    public function register(): void
    {
        $this->app->singleton(CheckerService::class,CheckerServiceImpl::class);
    }

    /**
     * Bootstrap services.
     */
    public function boot(): void
    {
        //
    }

    public function provides()
    {
        return [CheckerService::class]; // TODO: Change the autogenerated stub
    }
}
