<?php

namespace App\Providers\Client;

use App\Service\Client\Checker2Service;
use App\Service\Client\ServiceImpl\Checker2ServiceImpl;
use Illuminate\Contracts\Support\DeferrableProvider;
use Illuminate\Support\ServiceProvider;

class Checker2ServiceProvider extends ServiceProvider implements DeferrableProvider
{
    /**
     * Register services.
     */
    public function register(): void
    {
        $this->app->singleton(Checker2Service::class,Checker2ServiceImpl::class);
    }

    /**
     * Bootstrap services.
     */
    public function boot(): void
    {
        //
    }

    public function provides()
    {
        return [Checker2Service::class]; // TODO: Change the autogenerated stub
    }
}
