<?php

namespace App\Providers\Client;

use App\Service\Client\ServiceImpl\TransactionServiceImpl;
use App\Service\Client\TransactionService;
use Illuminate\Contracts\Support\DeferrableProvider;
use Illuminate\Support\ServiceProvider;

class TransactionServiceProvider extends ServiceProvider implements DeferrableProvider
{
    /**
     * Register services.
     */
    public function register(): void
    {
        $this->app->singleton(TransactionService::class,TransactionServiceImpl::class);

    }

    /**
     * Bootstrap services.
     */
    public function boot(): void
    {
        //
    }

    public function provides()
    {
        return [TransactionService::class]; // TODO: Change the autogenerated stub
    }
}
